### ISSUE TITLE
“今天上午9点23分我到成都”的例子运行结果和示例不一样

### ISSUE THREAD

**Issue by ctxhku** [Geekzhangwei/TimeNLP#1]
感谢作者无私的工作！想请问下，我在运行示例的时候，发现“今天上午9点23分我到成都”解析的结果是[['上午', (0, 2), '2022-01-26 10:00:00']]，好像并没有解析到后面的时间？谢谢Geekzhangwei大神的解答

**Comment by ctxhku** [comment]
把reg.pkl删除了再重新运行就好了

**Comment by Geekzhangwei** [comment]
有个业务脚本未更新上传，可以读一下源码。如果赶时间，可以自己尝试加一下。如果不着急，过年我会和更新一个版本。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月25日(周二) 下午3:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Geekzhangwei/TimeNLP] “今天上午9点23分我到成都”的例子运行结果和示例不一样 (Issue #1)




 
感谢作者无私的工作！想请问下，我在运行示例的时候，发现“今天上午9点23分我到成都”解析的结果是[['上午', (0, 2), '2022-01-26 10:00:00']]，好像并没有解析到后面的时间？谢谢Geekzhangwei大神的解答
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Geekzhangwei** [comment]
👍👍👍



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月25日(周二) 下午4:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Geekzhangwei/TimeNLP] “今天上午9点23分我到成都”的例子运行结果和示例不一样 (Issue #1)




 
把reg.pkl删除了再重新运行就好了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
